version: '3.8'

services:
  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    networks:
      - backend
  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=samesong
      - POSTGRES_PASSWORD=samesong_password
      - POSTGRES_DB=samesong
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - backend

  web:
    build: .
    command:  gunicorn --bind 0.0.0.0:5000 --workers 3 frontend.__init__:app
    expose:
      - "5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://samesong:samesong_password@db:5432/samesong
      - PYTHONPATH=/app
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
      - ./data/database:/app/data/database
    working_dir: /app
    networks:
      - frontend
      - backend

  worker:
    build: .
    command: celery -A processing.celeryProcess worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://samesong:samesong_password@db:5432/samesong
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
      - ./data/database:/app/data/database
    working_dir: /app
    networks:
      - backend


  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./security/samesong.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  postgres_data:
